@url = http://localhost:8080

POST {{url}}/autentica/login HTTP/1.1
content-type: application/json

{
 "senha": "12345678",
 "email": "adm@adm.com"
}

###
PUT {{url}}/api/fiscal/5 HTTP/1.1
content-type: application/json

{
  "nome": "Carolina Ribeiro Esteves da Silva Machado",
  "cpf": "815.436.148-50",
  "dataNascimento": "1993-09-23",
  "numeroTelefone": "9 1123-4321",
  "endereco": {
    "cep": "09878023",
    "logradouro": "Rua Antonieta",
    "numero": "78",
    "complemento": "APT 1",
    "cidade": "São Paulo",
    "estado": "SP"
  },
  "registroFiscal": "12.123.123",
  "dispositivo": {
    "codigo": "542-345",
    "tipoDispositivo": {
      "id": 1
    }
  },
  "conta": {
    "senha": "senha213",
    "email": "emailnovo@fiscal.com.br",
    "nivel": {
      "id": 3
    }
  }
}